//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID { get; set; }
        public int Washer { get; set; }
        public int Powder { get; set; }
        public int Drying { get; set; }
        public int Status { get; set; }
        public int Staff { get; set; }
        public double Amount { get; set; }
    
        public virtual Drying Drying1 { get; set; }
        public virtual ProcessingStatus ProcessingStatus { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Washers Washers { get; set; }
        public virtual Рowders Рowders { get; set; }
    }
}
